# Etapa 1: Construcción de la app
FROM node:24.6.0-alpine AS build

WORKDIR /app
COPY package.json yarn.lock ./

ENV NODE_OPTIONS=--max_old_space_size=8096 \
    GENERATE_SOURCEMAP=false

RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build:dev

# Etapa 2: Imagen final en nginx
FROM nginx:1.12-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY env.sh /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf


# No hace falta instalar bash
RUN chmod +x /usr/share/nginx/html/env.sh

EXPOSE 80

CMD ["/bin/sh", "-c", "/usr/share/nginx/html/env.sh && exec nginx -g 'daemon off;'"]

