export enum TranslateKeys {
  //Label
  LblId = "lbl_id",
  LblSellerCode = "lbl_seller_code",
  LblDocFrom = "lbl_doc_from",
  LblDocToNumeric = "lbl_doc_to_numeric",
  LblCurrentDoc = "lbl_current_doc",
  LblDocumentTypeFel = "lbl_document_type_fel",
  LblSerie = "lbl_serie",
  LblCreate = "lbl_create",
  LblCreatedBy = "lbl_created_by",
  LblUpdated = "lbl_updated",
  LblUpdatedBy = "lbl_updated_by",
  LblIsActive = "lbl_is_active",
  LblDocumentSequence = "lbl_document_sequence",
  LblRequired = "lbl_required",
  LblNew = "lbl_new",
  LblEdit = "lbl_edit",
  LblSave = "lbl_save",
  LblCancel = "lbl_cancel",
  LblDelete = "lbl_delete",
  LblDocType = "lbl_doc_type",
  LblTextGroupPanel = "lbl_text_group_panel",
  LblRole = "lbl_role",
  LblRoleCode = "lbl_role_code",
  LblRoleName = "lbl_role_name",
  LblRoleDescription = "lbl_role_description",
  LblGoToBeginning = "lbl_go_to_beginning",
  LblGoBack = "lbl_go_back",
  LblUnknownRute = "lbl_unknown_route",
  LblUserSession = "lbl_user_session",
  LblAccept = "lbl_accept",

  LblPermission = "lbl_permission",
  LblFilterMode = "lbl_filter_mode",
  LblUser = "lbl_User",
  LblApplication = "lbl_application",
  LblCleanFilter = "lbl_clean_filter",
  LblFilter = "lbl_filter",
  LblSaveChances = "lbl_save_changes",
  LblDiscardChanges = "lbl_discard_changes",
  LblResources = "lbl_resources",
  LblActionTotal = "lbl_action_total",
  LblPermitted = "lbl_permitted",
  LblDenied = "lbl_deneid",
  LblNotSet = "lbl_not_set",
  LblSet = "lbl_set",
  LblNoPermitsAvailable = "lbl_no_permits_available",
  LblHaveUnsavedChanges = "lbl_have_unsaved_changes",
  LblWarning = "lbl_warning",
  LblContinue = "lbl_continue",
  LblSureWantToContinue = "lbl_sure_want_to_continue",
  
  LblSureSaveChanges = "lbl_sure_save_changes",
  lblSureDiscardChanges = "lbl_sure_discard_changes",
  //Message
  MsgErrorHasEstablishedRange = "msg_error_has_established_range",
  MsgErrorMustGreaterBeginning = "msg_error_must_greater_beginning",
  MsgErrorUnexpectedError = "msg_error_unexpected_error",
  MsgErrorNetworkError = "msg_error_network_error",
  MsgInfonotFound = "msg_info_not_found",
  MsgInfoPathNotExist = "msg_info_path_not_exist",
  MsgInfoSessionExpired = "msg_info_session_expired",
  MsgSuccessfulProcess = "msg_successful_process",
}

export const TranslateDefaultText: Record<TranslateKeys, string> = {
  //Label
  [TranslateKeys.LblId]: "ID",
  [TranslateKeys.LblSellerCode]: "Seller Code",
  [TranslateKeys.LblDocFrom]: "From",
  [TranslateKeys.LblDocToNumeric]: "To",
  [TranslateKeys.LblCurrentDoc]: "Current",
  [TranslateKeys.LblDocumentTypeFel]: "Document Type Fel",
  [TranslateKeys.LblSerie]: "Serie",
  [TranslateKeys.LblCreate]: "Create",
  [TranslateKeys.LblCreatedBy]: "Create by",
  [TranslateKeys.LblUpdated]: "Updated",
  [TranslateKeys.LblUpdatedBy]: "Update by",
  [TranslateKeys.LblIsActive]: "Active",
  [TranslateKeys.LblDocumentSequence]: "Document Sequence",
  [TranslateKeys.LblRequired]: "Required",
  [TranslateKeys.LblNew]: "New",
  [TranslateKeys.LblEdit]: "Edit",
  [TranslateKeys.LblSave]: "Save",
  [TranslateKeys.LblCancel]: "Cancel",
  [TranslateKeys.LblDelete]: "Delete",
  [TranslateKeys.LblDocType]: "Type",
  [TranslateKeys.LblTextGroupPanel]: "Group columns...",
  [TranslateKeys.LblRole]: "Role",
  [TranslateKeys.LblRoleCode]: "Code",
  [TranslateKeys.LblRoleName]: "Name",
  [TranslateKeys.LblRoleDescription]: "Description",
  [TranslateKeys.LblUserSession]: "User Session",
  [TranslateKeys.LblAccept]: "Accept",

  [TranslateKeys.LblFilterMode]: "Filter Type",
  [TranslateKeys.LblUser]: "Users",
  [TranslateKeys.LblApplication]: "Application",
  [TranslateKeys.LblPermission]: "Permissions",
  [TranslateKeys.LblCleanFilter]: "Clean",
  [TranslateKeys.LblFilter]: "Filter",
  [TranslateKeys.LblSaveChances]: "Save changes",
  [TranslateKeys.LblDiscardChanges]: "Discard changes",
  [TranslateKeys.LblResources]: "Resources",
  [TranslateKeys.LblActionTotal]: "Actions total",
  [TranslateKeys.LblPermitted]: "Permitted",
  [TranslateKeys.LblDenied]: "Denied",
  [TranslateKeys.LblNotSet]: "Not set",
  [TranslateKeys.LblSet]: "Set",
  [TranslateKeys.LblNoPermitsAvailable]: "No permits available",
  [TranslateKeys.LblHaveUnsavedChanges]: "You have unsaved changes",
  [TranslateKeys.LblWarning]: "Warning",
  [TranslateKeys.LblContinue]: "Continue",
  [TranslateKeys.LblSureWantToContinue]: "Continue",
  [TranslateKeys.LblSureSaveChanges]: "Are you sure you want to save {count} permission changes?",
  [TranslateKeys.lblSureDiscardChanges]: "Are you sure you want to discard {count} unsaved changes?",
  //Message
  [TranslateKeys.MsgErrorHasEstablishedRange]:
    "It has to be within the established range",
  [TranslateKeys.MsgErrorMustGreaterBeginning]:
    "Must be greater at the beginning",
  [TranslateKeys.MsgErrorUnexpectedError]: "Unexpected error",
  [TranslateKeys.MsgErrorNetworkError]: "Network error",
  [TranslateKeys.MsgInfonotFound]:
    "The page you're trying to visit doesn't exist or has been moved. Check the URL or return to a safe location.",
  [TranslateKeys.LblGoToBeginning]: "Go to the beginning",
  [TranslateKeys.LblGoBack]: "Go back",
  [TranslateKeys.LblUnknownRute]: "Unknown Route",
  [TranslateKeys.MsgInfoPathNotExist]:
    "The path {route} does not exist or has been moved.",
  [TranslateKeys.MsgInfoSessionExpired]:
    "Your session has expired, please log in again.",
  [TranslateKeys.MsgSuccessfulProcess]: "Successful Process",
};
